# Usar una imagen base de Node.js para construir la app
FROM node:14 as build

# Establecer el directorio de trabajo
WORKDIR /usr/src/app

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto de la aplicación y construir
COPY . .
RUN npm run build

# Usar una imagen base para servir la aplicación
FROM nginx:alpine

# Copiar los archivos construidos a la carpeta de NGINX
COPY --from=build /usr/src/app/build /usr/share/nginx/html

# Exponer el puerto de NGINX
EXPOSE 80

# Comando para iniciar NGINX
CMD ["nginx", "-g", "daemon off;"]
