# Usa una imagen base de Node
FROM node:20

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos de configuración (package.json y package-lock.json)
COPY . .
# Instala las dependencias
RUN npm install

# Copia el resto de la aplicación
COPY . .

# Expone el puerto que tu aplicación usa
EXPOSE 5173

# Comando para iniciar la aplicación de react con vite
CMD ["npm", "run", "dev"]
